add support for json config file
hlavu/my-ssg pull request #22
Opened 2021-10-05 18:04 UTC by tuanthanh2067

2021-10-06 06:25 UTC, hlavu requested changes
And please update the README.md. Other parts are great!

2021-10-06 07:24 UTC, hlavu commented on bin/modules/readJson.js
> +    const lang = data.lang || "";
Please update the default value of `lang` to `en-CA`

2021-10-07 01:37 UTC, tuanthanh2067 commented
I've added what you requested!

2021-10-07 03:21 UTC, hlavu commented
Everything is perfect now. Thank you for your contribution.

2021-10-07 03:21 UTC, merged